
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/postgres?schema=kaptai
spring.r2dbc.username=test
spring.r2dbc.password=test
spring.r2dbc.properties.schema=kaptai

# Liquibase config for JDBC migrations  ? separate JDBC URL
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.url=jdbc:postgresql://localhost:5432/postgres
spring.liquibase.user=postgres
spring.liquibase.password=test
spring.liquibase.default-schema=kaptai
