

postgresql://postgres.fszuaxirnvnibhuuzgsd:[YOUR-PASSWORD]@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/pfh?schema=pfh
spring.r2dbc.username=test
spring.r2dbc.password=test